newIssueWelcomeComment: >
  ğŸ‰ğŸ‘Š **Issue iÃ§in teÅŸekkÃ¼rler** ğŸ‘Š ğŸ‰

  En kÄ±sa zamanda geliÅŸtiriciler size geri dÃ¶nÃ¼ÅŸ yapacaklardÄ±r. EÄŸer bu issue, bir yazÄ±m hatasÄ± ile ilgili ise bu hatayÄ± siz de dÃ¼zeltip pull request aÃ§abilirsiniz. KatkÄ±da bulunmadan Ã¶nce [CONTRIBUTING.md](https://github.com/jargonist/jargon.ist/blob/master/CONTRIBUTING.md) dokÃ¼manÄ±nÄ± okumayÄ± unutmayÄ±n.

newPRWelcomeComment: >
  ğŸ‰ğŸ‘Š **Pull request iÃ§in teÅŸekkÃ¼rler** ğŸ‘Š ğŸ‰

  Pull request iÃ§in teÅŸekkÃ¼r ederiz. Eger bu PR'da yeni bir jargon eklediyseniz, lÃ¼tfen [CONTRIBUTING.md](https://github.com/jargonist/jargon.ist/blob/master/CONTRIBUTING.md) dokÃ¼manÄ±nÄ± okuyup burada yazÄ±lanlara uyduÄŸunuza emin olun.

  YazmÄ±ÅŸ olduÄŸunuz dokÃ¼manda eÄŸer baÅŸka jargonlarÄ± da kullandÄ±ysanÄ±z ve bu jargonlar daha Ã¶nce [jargon.ist](https://jargon.ist) Ã¼zerinde yazÄ±lmÄ±ÅŸsa onlara link vermeniz faydalÄ± olacaktÄ±r. Bu jargonlar daha Ã¶nce tanÄ±mlanmadÄ±ysa ise yeni bir dokÃ¼man yazmasanÄ±z bile, en azÄ±ndan bu jargonlarÄ± linklemeniz topluluktan baÅŸkalarÄ±nÄ±n daha sonra tanÄ±mlamasÄ± iÃ§in yardÄ±mcÄ± olacaktÄ±r.

firstPRMergeComment: >
  ğŸ‰ğŸ‘Š **Pull request birleÅŸtirildi** ğŸ‘Š ğŸ‰

  Tebrikler! Pull request'in birleÅŸtirildi. YaptÄ±ÄŸÄ±n deÄŸiÅŸiklikler otomatik olarak birkaÃ§ dakika iÃ§inde [jargon.ist](https://jargon.ist) Ã¼zerinde yayÄ±nda olacak. EÄŸer yeni bir jargon eklediysen bu jargonun linki yine otomatik olarak Twitter Ã¼zerinde [@jargon_ist](https://twitter.com/jargon_ist) hesabÄ±nÄ±n takipÃ§ileri ile paylaÅŸÄ±lacak.
